# ==============================================================================
#  Software Information:
#      - Name:        Blender
#      - Homepage:    https://www.blender.org/
#      - Download:    https://www.blender.org/download/
# ==============================================================================
---
win_workman_blender_schema:
  name: Blender
  role: lineadicomando.win_workman.blender
  default_action: !!str on
  package:
    setup_file: blender-5.2.1-windows-x64.msi
    searchName: "Blender"
    version: "5.2.1"
    product_id: "{89F38CAB-6A94-4B76-9839-0AF9118C1E8E}"
  files:
    - filename: blender-5.2.1-windows-x64.msi
      url: https://ftp.halifax.rwth-aachen.de/blender/release/Blender5.2/blender-5.2.1-windows-x64.msi
      checksum: sha256:bebb90fc5bf7e3ec7ab4eb34f4c5a5b54e28e582a722152a47fd4ee66ec3c6fa
