# ==============================================================================
#  Software Information:
#      - Name:        DBeaver Community
#      - Homepage:    https://dbeaver.io
#      - Download:    https://github.com/dbeaver/dbeaver/releases
# ==============================================================================
---
win_workman_dbeaver_schema:
  name: DBeaver
  role: lineadicomando.win_workman.dbeaver
  default_action: !!str on
  package:
    setup_file: dbeaver-ce-26.2.0-windows-x86_64.exe
    searchName: "DBeaver*"
    version: 26.2.0
    provider: registry
    product_id: DBeaver
    install_args: "/S /allusers"
    uninstall_args: "/S"
    uninstall_via_helper: true
  files:
    - filename: dbeaver-ce-26.2.0-windows-x86_64.exe
      url: https://github.com/dbeaver/dbeaver/releases/download/26.2.0/dbeaver-ce-26.2.0-windows-x86_64.exe
      checksum: sha256:009e8a99be478261d09fdeb40ab5ef64bfe1f5faf79288cac670164719d921d2
  shortcuts:
    - description: "DBeaver"
      src: '%ProgramFiles%\DBeaver\dbeaver.exe'
      dest: '%Public%\Desktop\DBeaver.lnk'
      icon: '%ProgramFiles%\DBeaver\dbeaver.exe,0'
      directory: '%ProgramFiles%\DBeaver'
