# ==============================================================================
#  Software Information:
#      - Name:        Google Drive
#      - Homepage:    https://www.google.com/drive/download/
#      - Download:    https://dl.google.com/drive-file-stream/GoogleDriveSetup.exe
# ==============================================================================
---
win_workman_googledrive_shortcuts_schema:
  - description: "Google Drive"
    src: "%ProgramFiles%\\Google\\Drive File Stream\\launch.bat"
    dest: "%Public%\\Desktop\\Google Drive.lnk"
    icon: "%ProgramFiles%\\Google\\Drive File Stream\\drive_fs.ico,0"
    directory: "%ProgramFiles%\\Google\\Drive File Stream\\"

win_workman_googledrive_schema:
  name: Google Drive
  role: lineadicomando.win_workman.googledrive
  default_action: !!str on
  package:
    setup_file: GoogleDriveSetup.exe
    searchName: "Google Drive"
    provider: registry
    expected_return_code:
      - 0
      - 1638
    install_args:
      - --silent
      - --skip_launch_new
    uninstall_args:
      - --silent
  files:
    - filename: GoogleDriveSetup.exe
      url: https://dl.google.com/drive-file-stream/GoogleDriveSetup.exe
  shortcuts: >-
    {{
      win_workman_googledrive_shortcuts_schema if (
        win_workman_googledrive_desktop_shortcut | default(true) | bool
      ) else []
    }}
