---
- name: Logoff interactive sessions
  ansible.builtin.include_role:
    name: lineadicomando.win_workman.pkg_utils
    tasks_from: logoff

- name: Enable Windows widgets on taskbar
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Dsh
    name: AllowNewsAndInterests
    data: 1
    type: dword
    state: present
