---
- name: Dispatch action {{ win_workman_action or win_workman_lock_schema.default_action }}
  ansible.builtin.include_role:
    name: lineadicomando.win_workman.lock
    tasks_from: "act_{{ win_workman_action or win_workman_lock_schema.default_action }}"
