# ==============================================================================
#  Software Information:
#      - Name:        Visual Studio Code
#      - Homepage:    https://code.visualstudio.com/
#      - Download:    https://code.visualstudio.com/Download
# ==============================================================================
---
win_workman_vscode_shortcuts_schema:
  - description: "Visual Studio Code"
    src: "%ProgramFiles%\\Microsoft VS Code\\Code.exe"
    arguments: ""
    dest: '%Public%\Desktop\Visual Studio Code.lnk'
    icon: "%ProgramFiles%\\Microsoft VS Code\\Code.exe,0"
    directory: "%ProgramFiles%\\Microsoft VS Code"

win_workman_vscode_schema:
  name: Visual Studio Code
  role: lineadicomando.win_workman.vscode
  default_action: !!str on
  package:
    setup_file: VSCodeSetup-x64-1.137.0.exe
    searchName: "Microsoft Visual Studio Code"
    version: "1.137.0"
    install_args:
      - /VERYSILENT
      - /TASKS=desktopicon,addtopath
      - /MERGETASKS=!runcode
    uninstall_args:
      - /VERYSILENT
  files:
    - filename: VSCodeSetup-x64-1.137.0.exe
      url: https://vscode.download.prss.microsoft.com/dbazure/download/stable/645f29cc3176500b4b5762ba887cf2a7f0ffdf2c/VSCodeSetup-x64-1.137.0.exe
      checksum: sha256:7aa601ca69dfa3ddf020d3df4e35ffaccbb02748cc31587580f215b143586ad3
  shortcuts: >-
    {{
      win_workman_vscode_shortcuts_schema if (
        win_workman_vscode_shortcuts | bool | default(false)
      ) else []
    }}
