# ==============================================================================
#  Software Information:
#      - Name:        WinMerge
#      - Homepage:    https://winmerge.org/
#      - Download:    https://winmerge.org/downloads/
# ==============================================================================
---
win_workman_winmerge_schema:
  name: WinMerge
  package:
    setup_file: WinMerge-2.16.56-x64-Setup.exe
    searchName: "WinMerge*"
    version: "2.16.56"
    install_args:
      - /VERYSILENT
      - /SUPPRESSMSGBOXES
      - /NORESTART
    uninstall_args:
      - /VERYSILENT
      - /SUPPRESSMSGBOXES
      - /NORESTART
  files:
    - filename: WinMerge-2.16.56-x64-Setup.exe
      url: https://github.com/WinMerge/winmerge/releases/download/v2.16.56/WinMerge-2.16.56-x64-Setup.exe
      checksum: sha256:51840b2f7b6227f6b88acfb10b0fefdecf3ecf959b665ad7fefc372fb1e8bc60
  shortcuts: []

win_workman_schema_role_name: lineadicomando.win_workman.winmerge
win_workman_schema_dir: winmerge
