---
- name: Dispatch action {{ win_workman_action or win_workman_ms_account_schema.default_action }}
  ansible.builtin.include_role:
    name: lineadicomando.win_workman.ms_account
    tasks_from: "act_{{ win_workman_action or win_workman_ms_account_schema.default_action }}"
