---
- name: Dispatch action {{ win_workman_action or win_workman_wol_schema.default_action }}
  ansible.builtin.include_role:
    name: lineadicomando.win_workman.wol
    tasks_from: "act_{{ win_workman_action or win_workman_wol_schema.default_action }}"
