---
win_workman_secure_ssh_schema:
  name: Secure SSH Connection
  role: lineadicomando.win_workman.secure_ssh
  default_action: !!str on

win_workman_secure_ssh_auth_keys_path: C:\ProgramData\ssh\administrators_authorized_keys
win_workman_secure_ssh_config_path: C:\ProgramData\ssh\sshd_config
