# ==============================================================================
#  Software Information:
#      - Name:        Git for Windows
#      - Homepage:    https://gitforwindows.org/
#      - Download:    https://github.com/git-for-windows/git/releases
# ==============================================================================
---
win_workman_git_schema:
  name: Git
  role: lineadicomando.win_workman.git
  default_action: !!str on
  package:
    setup_file: Git-2.55.0.5-64-bit.exe
    searchName: "Git"
    version: "2.55.0.5"
    install_args:
      - /VERYSILENT
      - /NORESTART
      - /NOCANCEL
      - /SP-
    uninstall_args:
      - /VERYSILENT
      - /NORESTART
  files:
    - filename: Git-2.55.0.5-64-bit.exe
      url: https://github.com/git-for-windows/git/releases/download/v2.55.0.windows.5/Git-2.55.0.5-64-bit.exe
      checksum: sha256:d065a4e23c3d9a6b5073d609b5be0830227ec3ca053c083ba385061ddfaf94c6
