# ==============================================================================
#  Software Information:
#      - Name:        Microsoft Edge
#      - Homepage:    https://www.google.com/intl/en_US/chrome/
#      - Download:    https://www.microsoft.com/it-it/edge/business/download
# ==============================================================================
---
win_workman_edge_before_act_ps_script: |
  $Ansible.Changed = $false
  $process = Get-Process -Name msedge -ErrorAction SilentlyContinue
  if ($process) {
      Stop-Process -InputObject $process -Force:$true
      $Ansible.Changed = $true
  }

win_workman_edge_shortcut_arguments: >-
  {{
    (
      ("--disable-search-engine-choice-screen " if win_workman_edge_shortcut_no_first_run | bool else "") +
      ("--no-default-browser-check " if win_workman_edge_shortcut_no_first_run | bool else "") +
      ("--no-first-run " if win_workman_edge_shortcut_no_first_run | bool else "") +
      win_workman_edge_shortcut_url
    ) | trim
  }}
win_workman_edge_arch: >-
  {{
    "32bit" if (
      "32bit" in (win_workman_task_argv | default([]))
    ) else "64bit"
  }}

win_workman_edge_setup_file:
  64bit: MicrosoftEdgeEnterpriseX64.msi
  32bit: MicrosoftEdgeEnterpriseX86.msi

win_workman_edge_url:
  64bit: https://msedge.sf.dl.delivery.mp.microsoft.com/filestreamingservice/files/1e31b6ea-8368-4a80-b494-2ffa12a70507/MicrosoftEdgeEnterpriseX64.msi
  32bit: https://msedge.sf.dl.delivery.mp.microsoft.com/filestreamingservice/files/e50790e3-cf2e-4023-a596-00ac90788516/MicrosoftEdgeEnterpriseX86.msi

win_workman_edge_checksum:
  64bit: sha256:022d78c7b2dfbe62dc97a1e5b6f7e373b2c90d91a484a98548928575c0aa2ac4
  32bit: sha256:24566ecb7bc9128193c3d93b82e50bcd0c5ba9241960b683b81fe48262a646a7

win_workman_edge_program_file:
  64bit: "%ProgramFiles%"
  32bit: "%ProgramFiles(x86)%"

win_workman_edge_shortcuts_schema:
  - description: "Microsoft Edge"
    src: "{{ win_workman_edge_program_file[win_workman_edge_arch] }}\\Microsoft\\Edge\\Application\\msedge.exe"
    arguments: "{{ win_workman_edge_shortcut_arguments }}"
    dest: "%Public%\\Desktop\\Microsoft Edge.lnk"
    icon: "{{ win_workman_edge_program_file[win_workman_edge_arch] }}\\Microsoft\\Edge\\Application\\msedge.exe,0"
    directory: "{{ win_workman_edge_program_file[win_workman_edge_arch] }}\\Microsoft\\Edge\\Application\\"
  - description: "Microsoft Edge"
    src: "{{ win_workman_edge_program_file[win_workman_edge_arch] }}\\Microsoft\\Edge\\Application\\msedge.exe"
    arguments: "{{ win_workman_edge_shortcut_arguments }}"
    dest: "%ProgramData%\\Microsoft\\Windows\\Start Menu\\Programs\\Microsoft Edge.lnk"
    icon: "{{ win_workman_edge_program_file[win_workman_edge_arch] }}\\Microsoft\\Edge\\Application\\msedge.exe,0"
    directory: "{{ win_workman_edge_program_file[win_workman_edge_arch] }}\\Microsoft\\Edge\\Application\\"

win_workman_edge_schema:
  name: Microsoft Edge
  default_action: !!str on
  package:
    setup_file: "{{ win_workman_edge_setup_file[win_workman_edge_arch] }}"
    searchName: "Microsoft Edge"
    version: 148.0.3967.96
    before_install_ps_script: "{{ win_workman_edge_before_act_ps_script }}"
  files:
    - filename: "{{ win_workman_edge_setup_file[win_workman_edge_arch] }}"
      url: "{{ win_workman_edge_url[win_workman_edge_arch] }}"
      checksum: "{{ win_workman_edge_checksum[win_workman_edge_arch] }}"
  shortcuts: >-
    {{
      win_workman_edge_shortcuts_schema if (
        win_workman_edge_shortcuts | bool | default(false)
      ) else []
    }}

win_workman_schema_role_name: lineadicomando.win_workman.edge
win_workman_schema_dir: edge
