# ==============================================================================
#  Software Information:
#      - Name:        Python 3.14
#      - Homepage:    https://www.python.org/
#      - Download:    https://www.python.org/downloads/windows/
# ==============================================================================
---
win_workman_python314_schema:
  name: Python 3.14
  role: lineadicomando.win_workman.python314
  default_action: !!str on
  package:
    setup_file: python-3.14.7-amd64.exe
    version: "3.14.7150.0"
    provider: registry
    product_id: "{97b6de30-6082-48d1-9bb4-9f43296531a4}"
    searchName: "Python 3.14.7 (64-bit)"
    install_args: /quiet InstallAllUsers=1 PrependPath=1 Include_launcher=0 Shortcuts=1
    uninstall_args: /quiet
    cleanup_paths:
      - '%ProgramFiles%\Python314'
      - '%ProgramData%\Microsoft\Windows\Start Menu\Programs\Python 3.14'
      - '%Public%\Desktop\Python 3.14 (64-bit).lnk'
      - '%Public%\Desktop\IDLE (Python 3.14 64-bit).lnk'
  files:
    - filename: python-3.14.7-amd64.exe
      url: https://www.python.org/ftp/python/3.14.7/python-3.14.7-amd64.exe
      checksum: sha256:9d9eb2709ef81bf5cd30db3c2096bdbc4ea10087c22e62f27d356b36f6ae9649
  shortcuts:
    - description: "Launches the Python 3.14 interpreter"
      src: '%ProgramFiles%\Python314\python.exe'
      dest: '%Public%\Desktop\Python 3.14 (64-bit).lnk'
      icon: '%ProgramFiles%\Python314\python.exe,0'
      directory: '%ProgramFiles%\Python314'
    - description: "Launches IDLE, the interactive environment for Python 3.14"
      src: '%ProgramFiles%\Python314\pythonw.exe'
      arguments: '"%ProgramFiles%\Python314\Lib\idlelib\idle.pyw"'
      dest: '%Public%\Desktop\IDLE (Python 3.14 64-bit).lnk'
      icon: '%SystemRoot%\Installer\{59230DE7-62CA-4C71-B6F8-F8C26E7A927D}\idle.exe,0'
      directory: '%ProgramFiles%\Python314'
