---
- name: Dispatch action run
  ansible.builtin.include_role:
    name: lineadicomando.win_workman.wu
    tasks_from: act_run
  when: win_workman_action == "run"

- name: Dispatch action on
  ansible.builtin.include_role:
    name: lineadicomando.win_workman.wu
    tasks_from: act_on
  when: win_workman_action == "on"

- name: Dispatch action off
  ansible.builtin.include_role:
    name: lineadicomando.win_workman.wu
    tasks_from: act_off
  when: win_workman_action == "off"

- name: Dispatch action pause_on
  ansible.builtin.include_role:
    name: lineadicomando.win_workman.wu
    tasks_from: act_pause
  when: win_workman_action == "pause"

- name: Dispatch action pause_off
  ansible.builtin.include_role:
    name: lineadicomando.win_workman.wu
    tasks_from: act_resume
  when: win_workman_action == "resume"

- name: Dispatch action max_pause_days
  ansible.builtin.include_role:
    name: lineadicomando.win_workman.wu
    tasks_from: act_max_pause_days
  when: win_workman_action == "max_pause_days"

- name: Dispatch action is_paused
  ansible.builtin.include_role:
    name: lineadicomando.win_workman.wu
    tasks_from: act_is_paused
  when: win_workman_action == "is_paused"

- name: Dispatch action policy_standard
  ansible.builtin.include_role:
    name: lineadicomando.win_workman.wu
    tasks_from: act_policy_standard
  when: win_workman_action == "policy_standard"
