# ==============================================================================
#  Software Information:
#      - Name:        Google Credential Provider for Windows (GCPW)
#      - Homepage:    https://tools.google.com/dlpage/gcpw
#      - Download:    https://dl.google.com/credentialprovider/gcpwstandaloneenterprise64.msi
# ==============================================================================
---
win_workman_gcpw_arch: >-
  {{
    "32bit" if (
      "32bit" in (win_workman_task_argv | default([]))
    ) else "64bit"
  }}

win_workman_gcpw_setup_filename:
  64bit: gcpwstandaloneenterprise64.msi
  32bit: gcpwstandaloneenterprise.msi

win_workman_gcpw_url:
  64bit: https://dl.google.com/credentialprovider/gcpwstandaloneenterprise64.msi
  32bit: https://dl.google.com/credentialprovider/gcpwstandaloneenterprise.msi

win_workman_gcpw_schema:
  name: Google Credential Provider for Windows
  role: lineadicomando.win_workman.gcpw
  default_action: !!str on
  package:
    setup_file: "{{ win_workman_gcpw_setup_filename[win_workman_gcpw_arch] }}"
    searchName: "Google Credential Provider for Windows"
    install_args:
      - /quiet
    uninstall_args:
      - /quiet
  files:
    - filename: "{{ win_workman_gcpw_setup_filename[win_workman_gcpw_arch] }}"
      url: "{{ win_workman_gcpw_url[win_workman_gcpw_arch] }}"
  shortcuts: []
