# ==============================================================================
#  Software Information:
#      - Name:        Python 3.12
#      - Homepage:    https://www.python.org/
#      - Download:    https://www.python.org/downloads/windows/
# ==============================================================================
---
win_workman_python312_schema:
  name: Python 3.12
  role: lineadicomando.win_workman.python312
  default_action: !!str on
  package:
    setup_file: python-3.12.10-amd64.exe
    version: "3.12.10150.0"
    provider: registry
    searchName: "Python 3.12.10 (64-bit)"
    install_args: /quiet InstallAllUsers=1 PrependPath=1 Include_launcher=0
    uninstall_args: /quiet
  files:
    - filename: python-3.12.10-amd64.exe
      url: https://www.python.org/ftp/python/3.12.10/python-3.12.10-amd64.exe
      checksum: sha256:67b5635e80ea51072b87941312d00ec8927c4db9ba18938f7ad2d27b328b95fb
  cleanup_paths:
    - '%ProgramFiles%\Python312'
    - '%ProgramData%\Microsoft\Windows\Start Menu\Programs\Python 3.12'
    - '%Public%\Desktop\Python 3.12 (64-bit).lnk'
    - '%Public%\Desktop\IDLE (Python 3.12 64-bit).lnk'
  shortcuts:
    - description: "Launches the Python 3.12 interpreter"
      src: '%ProgramFiles%\Python312\python.exe'
      dest: '%Public%\Desktop\Python 3.12 (64-bit).lnk'
      icon: '%ProgramFiles%\Python312\python.exe,0'
      directory: '%ProgramFiles%\Python312'
    - description: "Launches IDLE, the interactive environment for Python 3.12"
      src: '%ProgramFiles%\Python312\pythonw.exe'
      arguments: '"%ProgramFiles%\Python312\Lib\idlelib\idle.pyw"'
      dest: '%Public%\Desktop\IDLE (Python 3.12 64-bit).lnk'
      icon: '%SystemRoot%\Installer\{75485683-EF03-41E6-BF21-D1491694548C}\idle.exe,0'
      directory: '%ProgramFiles%\Python312'
