# ==============================================================================
#  Software Information:
#      - Name:        Veyon
#      - Homepage:    https://veyon.io
#      - Download:    https://veyon.io/it/download/
# ==============================================================================
---
win_workman_veyon_master_args: >-
  {{
      [] if (
      ("master" in (win_workman_task_argv | default([])))
      or
      (win_workman_veyon_master | default(false) | bool)
    ) else ['/NoMaster']
  }}

win_workman_veyon_schema:
  name: Veyon
  default_action: !!str on
  package:
    setup_file: veyon-4.10.3.0-win64-setup.exe
    searchName: "Veyon"
    version: "4.10.3.0"
    product_id: Veyon
    provider: registry
    uninstall_before_upgrade: true
    install_args: >-
      {{
        ['/S'] + win_workman_veyon_master_args
      }}
    uninstall_args: "/S"
    uninstall_via_helper: true
  files:
    - filename: veyon-4.10.3.0-win64-setup.exe
      url: https://github.com/veyon/veyon/releases/download/v4.10.3/veyon-4.10.3.0-win64-setup.exe
      checksum: sha256:e07aa02cd1e9027690e1a4158498b8ba8913d312e16c800f78607ad83951aa40

win_workman_schema_role_name: lineadicomando.win_workman.veyon
win_workman_schema_dir: veyon
