# ==============================================================================
#  Software Information:
#      - Name:        Veyon
#      - Homepage:    https://veyon.io
#      - Download:    https://veyon.io/it/download/
# ==============================================================================
---
win_workman_veyon_master_args: >-
  {{
      [] if (
      ("master" in (win_workman_task_argv | default([])))
      or
      (win_workman_veyon_master | default(false) | bool)
    ) else ['/NoMaster']
  }}

win_workman_veyon_schema:
  name: Veyon
  role: lineadicomando.win_workman.veyon
  default_action: !!str on
  package:
    setup_file: veyon-4.11.2.0-win64-setup.exe
    searchName: "Veyon"
    version: "4.11.2.0"
    product_id: Veyon
    provider: registry
    uninstall_before_upgrade: true
    install_args: >-
      {{
        ['/S'] + win_workman_veyon_master_args
      }}
    uninstall_args: "/S"
    uninstall_via_helper: true
  files:
    - filename: veyon-4.11.2.0-win64-setup.exe
      url: https://github.com/veyon/veyon/releases/download/v4.11.2/veyon-4.11.2.0-win64-setup.exe
      checksum: sha256:7ec3f0689f995fe7c79d3f5b106e85dade089ab24f534e92a168543197f0e428
