# ==============================================================================
#  Software Information:
#      - Name:        7-Zip
#      - Homepage:    https://www.7-zip.org/
#      - Download:    https://www.7-zip.org/
# ==============================================================================
---
win_workman_7zip_arch: >-
  {{
    "32bit" if (
      "32bit" in (win_workman_task_argv | default([]))
    ) else "64bit"
  }}

win_workman_7zip_setup_filename:
  32bit: 7z2603.msi
  64bit: 7z2603-x64.msi

win_workman_7zip_url:
  64bit: https://7-zip.org/a/7z2603-x64.msi
  32bit: https://7-zip.org/a/7z2603.msi

win_workman_7zip_checksum:
  64bit: sha256:c0680064d698a62dd4a5a47f403db356a6531a5473e4c4b1d090ea2590513926
  32bit: sha256:23b5a8843b09db629b6f6a63364bae5430f66d6ecd4b38e11e1661bfaff5d2c6

win_workman_7zip_cleanup_paths:
  64bit: '%ProgramFiles%\7-Zip'
  32bit: '%ProgramFiles(x86)%\7-Zip'

win_workman_p7zip_schema:
  name: "7-Zip 26.03"
  role: lineadicomando.win_workman.p7zip
  default_action: !!str on
  package:
    provider: msi
    setup_file: "{{ win_workman_7zip_setup_filename[win_workman_7zip_arch] }}"
    version: "26.03.00.0"
    searchName: "7-Zip 26.03*"
    cleanup_paths:
      - "{{ win_workman_7zip_cleanup_paths[win_workman_7zip_arch] }}"
  files:
    - filename: "{{ win_workman_7zip_setup_filename[win_workman_7zip_arch] }}"
      url: "{{ win_workman_7zip_url[win_workman_7zip_arch] }}"
      checksum: "{{ win_workman_7zip_checksum[win_workman_7zip_arch] }}"
