# ==============================================================================
#  Software Information:
#      - Name:        VirtIO Win Guest Tools
#      - Homepage:    https://virtio-win.github.io/
#      - Download:    https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/
# ==============================================================================
---
win_workman_virtiogt_schema:
  name: VirtIO Win Guest Tools
  package:
    setup_file: virtio-win-guest-tools.exe
    searchName: "Virtio-win-guest-tools"
    version: "0.1.285"
    install_args: "/s /qn /norestart"
    uninstall_args: "/s /qn /norestart"
  files:
    - filename: virtio-win-guest-tools.exe
      url: https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/archive-virtio/virtio-win-0.1.285-1/virtio-win-guest-tools.exe
      checksum: sha256:c8b4a9fe87e1fc5d8e843495e082dea53420587fe04740b1084d85089343f04d

win_workman_schema_role_name: lineadicomando.win_workman.virtiogt
win_workman_schema_dir: virtiogt
