# ==============================================================================
#  Software Information:
#      - Name:        VirtIO Win Guest Tools
#      - Homepage:    https://virtio-win.github.io/
#      - Download:    https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/
# ==============================================================================
---
win_workman_virtiogt_schema:
  name: VirtIO Win Guest Tools
  role: lineadicomando.win_workman.virtiogt
  default_action: !!str on
  package:
    setup_file: virtio-win-guest-tools.exe
    searchName: "Virtio-win-guest-tools"
    version: "0.1.302"
    install_args: "/s /qn /norestart"
    uninstall_args: "/s /qn /norestart"
  files:
    - filename: virtio-win-guest-tools.exe
      url: https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/archive-virtio/virtio-win-0.1.302-1/virtio-win-guest-tools.exe
      checksum: sha256:d8ae9ea1e943384ac195e012cd36f82c3161620e5fc9529be4e42e6f420e222d
