# ==============================================================================
#  Software Information:
#      - Name:        GeoGebra Classic 5
#      - Homepage:    https://www.geogebra.org/
#      - Download:    https://geogebra.github.io/docs/reference/en/GeoGebra_Installation/
# ==============================================================================
---
win_workman_geogebra5_schema:
  name: GeoGebra Classic 5
  role: lineadicomando.win_workman.geogebra5
  default_action: !!str on
  package:
    setup_file: GeoGebra-Windows-Installer-5-4-929-3.msi
    searchName: "GeoGebra 5"
    version: "5.4.929.3"
    install_args: "ALLUSERS=2 /qn"
  files:
    - filename: GeoGebra-Windows-Installer-5-4-929-3.msi
      url: https://download.geogebra.org/installers/5.4/GeoGebra-Windows-Installer-5-4-929-3.msi
      checksum: sha256:b7b9ff3fa84e017f4750562abfd882030c434b59eabf6bcb6614e3a7d655dc56
