---
- name: Dispatch action {{ win_workman_action or win_workman_oobe_schema.default_action }}
  ansible.builtin.include_role:
    name: lineadicomando.win_workman.oobe
    tasks_from: "act_{{ win_workman_action or win_workman_oobe_schema.default_action }}"
