# ==============================================================================
#  Software Information:
#      - Name:        Zoom Workplace
#      - Homepage:    https://zoom.us
#      - Download:    https://zoom.us/download/admin
# ==============================================================================
---
win_workman_zoom_schema:
  name: Zoom
  role: lineadicomando.win_workman.zoom
  default_action: !!str on
  package:
    setup_file: ZoomInstallerFull64bit.msi
    searchName: "Zoom Workplace (64-bit)"
    version: "7.1.46825"
    product_id: "{92F7BF02-3608-401D-ABF0-1D9F1965FA42}"
  files:
    - filename: ZoomInstallerFull64bit.msi
      url: https://cdn.zoom.us/prod/7.1.8.46825/x64/ZoomInstallerFull.msi
      checksum: sha256:caa80801ac68d327014da0a6e387f37976d1e405e8a02ea40ce5b73cf47c3302
