# ==============================================================================
#  Software Information:
#      - Name:        Zoom Workplace
#      - Homepage:    https://zoom.us
#      - Download:    https://zoom.us/download/admin
# ==============================================================================
---
win_workman_zoom_schema:
  name: Zoom
  role: lineadicomando.win_workman.zoom
  default_action: !!str on
  package:
    setup_file: ZoomInstallerFull64bit.msi
    searchName: "Zoom Workplace (64-bit)"
    version: "7.2.48556"
    product_id: "{518AB954-56D5-4942-802D-ED4A1DAA61FD}"
  files:
    - filename: ZoomInstallerFull64bit.msi
      url: https://cdn.zoom.us/prod/7.2.1.48556/x64/ZoomInstallerFull.msi
      checksum: sha256:b0dac9fa5237d2e18144ca723644460e7cc26675e5d3db0f89fdfe47ad8c429b
